import type { Metadata } from 'next';
import React from 'react';

import AppProviders from '@/providers/app-provider';

import '@/styles/globals.css';
import { rubik } from '@/config/font.config';
import { cn } from '@/lib';

//-----------------------------------------------------------------------------------------------

export const metadata: Metadata = {
  title: 'Social Network',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen block relative h-full w-full',
          rubik.className
        )}
      >
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
